### ISSUE TITLE
looks great, but may you share some paper or another description pls

### ISSUE THREAD

**Issue by Sandy4321** [gaohuang/S-WMD#1]
may help find some description for example paper about this?

**Comment by taineleau-zz** [comment]
Maybe you would like to check this: 

https://channel9.msdn.com/Events/Neural-Information-Processing-Systems-Conference/Neural-Information-Processing-Systems-Conference-NIPS-2016/Supervised-Word-Movers-Distance

:D

**Comment by cg563** [comment]
We added links to the paper and the NIPS oral presentation.
